// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	SessionScopes = "session.Scopes"
)

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *string `json:"ok,omitempty"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	Errors  int     `json:"errors"`
	Message *string `json:"message,omitempty"`
	Synced  int     `json:"synced"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt time.Time `json:"createdAt"`
	Done      bool      `json:"done"`
	Id        string    `json:"id"`
	Title     string    `json:"title"`
	UserId    string    `json:"userId"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Import tasks from Google Tasks as todos
	// (POST /api/tasks/pull)
	PullFromGoogleTasks(w http.ResponseWriter, r *http.Request)
	// Push local todos to Google Tasks
	// (POST /api/tasks/push)
	PushToGoogleTasks(w http.ResponseWriter, r *http.Request)
	// List all todos for the authenticated user
	// (GET /api/todos)
	ListTodos(w http.ResponseWriter, r *http.Request)
	// Create a new todo
	// (POST /api/todos)
	CreateTodo(w http.ResponseWriter, r *http.Request)
	// Delete a todo by ID
	// (DELETE /api/todos/{id})
	DeleteTodo(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Import tasks from Google Tasks as todos
// (POST /api/tasks/pull)
func (_ Unimplemented) PullFromGoogleTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Push local todos to Google Tasks
// (POST /api/tasks/push)
func (_ Unimplemented) PushToGoogleTasks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all todos for the authenticated user
// (GET /api/todos)
func (_ Unimplemented) ListTodos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new todo
// (POST /api/todos)
func (_ Unimplemented) CreateTodo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a todo by ID
// (DELETE /api/todos/{id})
func (_ Unimplemented) DeleteTodo(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PullFromGoogleTasks operation middleware
func (siw *ServerInterfaceWrapper) PullFromGoogleTasks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PullFromGoogleTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PushToGoogleTasks operation middleware
func (siw *ServerInterfaceWrapper) PushToGoogleTasks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PushToGoogleTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTodos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTodo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/pull", wrapper.PullFromGoogleTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/tasks/push", wrapper.PushToGoogleTasks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/todos", wrapper.ListTodos)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/todos", wrapper.CreateTodo)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/todos/{id}", wrapper.DeleteTodo)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWwW7jNhD9FYLtURs5TU+6ZbttYXTRDbLpKQgKRhxbXEsclhxloRr692JI2ZYipbto",
	"k6BAb7JJvnnzHjkze1li49CCpSCLvfQQHNoA8cdbpa/hjxYC8a8SLYGNn8q52pSKDNr8U0DL/4Wygkbx",
	"17ceNrKQ3+Qn6DythvxH79FfD0Fk3/eZ1BBKbxyDyUKu7YOqjRZ+CNxn8jerWqrQmz9Bvx6RX5EExwVL",
	"HAG05D3DcUb/wYMiuEGNI5GcRweeTBKQDNXAH42x78FuqZLFeSapcyALGcgbu42wnK3xnN7tcOjuuA3v",
	"P0EZhZhynkUDXo5hZ/gzqA+7p3Fw95UgHztbXkNoa3qCTBgBGUuwBc/nGghBbWEhSiZDZ8tk8+Nzj2Qa",
	"NmaHSEuCsTlzamU0Tl9G1hv0jSJZSK0I3pBpQGZzVhrtmO49Yg3K8orRi2kcnZ+ttAH8Wi8rPM7PcG7D",
	"5gPeQCQbpTBPm0WEsvWGuo98W1PSAUIw6YEYvt4l4s4wlFUNn1bO/X7Yc4RUzvwCXXodxm6iltNXwgoL",
	"5ZzQ0KAN5BUZuxUfHNjLq/Ub7c0DWKHhAWp0DVgSnw1VfOJeBTgmNgBdXq1lJh/AJ6pydXZ+tmLR0IFV",
	"zshCXpytzi5kJp2iKiaWK2dyUmEXctfWdbQb02Nk02NtYL3lVVvXP3lsfkbc1nDDJ2Q2LXjfrVbPVmBG",
	"j2OhujAZ4YflTH6/On8K70gwn9TBeOjiNcuhSMKxSUKVJYQgCHdgJzdOFreju3Z7199lMrRNo3zHxb1x",
	"6ElEt8TGY3PAjG4IxYgaQ0Sc+Bqqv/M1VDf4H3E1VP8/V2PWNZaqTvYJwomvIzuju8VebmHByPcm0E3c",
	"8S8NNARN+JI2sTecupryXnVLEjErgZvDzfxHrn61lDGYqg9CbtALqmA6hwhuCkxk+TmcxhKZGgoEeou6",
	"e7ZLNZ97+mnvIt9CP7Pw/NkIJOfmTiViOmqXjFp92ajRjPvC3iZ6QgkLnweOk3eR743uU4etgWDu7Lv4",
	"/+CsU141QMAz1u3Q07knnjp6HCCmrmQjhR9PH3cvWDVH0+aCbykv/dL6pzBCRe3FfSfW75hN/1cAAAD/",
	"/xQajbIDDQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
